Fix download failed on windows
$ multiwerf update 1.2 ea
```
multiwerf dev
Self-update has been delayed: 1h37m19s left till next attempt
GC: Actual versions: [v1.0.13 v1.0.13+fix4 v1.0.13+fix5 v1.1.16+fix10 v1.1.16+fix8 v1.1.19+fix3 v1.1.22+fix37 v1.1.23+fix13 v1.1.23+fix6 v1.1.8+fix20 v1.2.4+fix18 v1.2.5+fix1 v1.2.5+fix3]
GC: Local versions:  [v1.0.13 v1.1.16+fix8 v1.2.5+fix1 v1.2.5+fix3]
GC: Nothing to clean
The version v1.2.10+fix31 is the actual for channel 1.2/ea
Downloading the version v1.2.10+fix31 ...
[s3] Downloading the version v1.2.10+fix31 failed: unable to rename "C:\\Users\\foobar\\.multiwerf\\tmp\\v1.2.10+fix31-458040835\\werf-windows-amd64-v1.2.10+fix31.exe.ac5b9ab4-eb54-476a-bc5f-4483c7984231" to "C:\\Users\\foobar\\.multiwerf\\tmp\\v1.2.10+fix31-458040835\\werf-windows-amd64-v1.2.10+fix31.exe": rename C:\Users\foobar\.multiwerf\tmp\v1.2.10+fix31-458040835\werf-windows-amd64-v1.2.10+fix31.exe.ac5b9ab4-eb54-476a-bc5f-4483c7984231 C:\Users\foobar\.multiwerf\tmp\v1.2.10+fix31-458040835\werf-windows-amd64-v1.2.10+fix31.exe: The process cannot access the file because it is being used by another process.
Error: werf 1.2/ea: https://dl.bintray.com/flant/werf/v1.2.10+fix31/SHA256SUMS download error: bad status: 404 Not Found
```